spring:
  application:
    name: netflix-like

  datasource:
    url: jdbc:postgresql://localhost:5438/netflix-like
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml

logging:
  level:
    root: INFO
    org.springframework.web: INFO